# Default values for ms-orders.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
image:
  repository: registy.arbwallet.host
  tag: dev
  pullPolicy: IfNotPresent

env:
  REDIS_HOST: redis-pro-master
  ADMIN_USER_ID: 2
  DD_APM: true
  DD_TRACE_ANALYTICS_ENABLED: true
  DD_RUNTIME_METRICS_ENABLED: true
  DD_LOGS_INJECTION: true

envBySecret:
  - name: REDIS_PASS
    secret: redis-pro
    key: redis-password

envFromSecret:
  - ms-common
  - sendgrid

apmEnable: true

resources:
  limits:
    cpu: 800m
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 15
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 90


internalPort: 3000

enableProbe: true
probePath: /health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10